// Twin: backend/tests/services/test_retirement_planning_service.py
// ::test_estimate_social_security_monthly_matches_frontend_golden_table
//
// Golden cents were generated by RUNNING the backend
// _estimate_social_security_monthly (never hand-computed). The backend
// rounds to cents while the frontend estimator does not, hence ±0.005.
import { describe, expect, it } from 'vitest'
import { estimateSocialSecurityMonthly } from '../MoneyRetirementPanel'

const goldenRows: Array<{
  label: string
  annualEarnings: number
  claimAge: number
  stopWorkAge: number | null
  expected: number
}> = [
  {
    label: 'low earner at FRA',
    annualEarnings: 12_000,
    claimAge: 67,
    stopWorkAge: null,
    expected: 900.0,
  },
  {
    label: 'middle earner at FRA',
    annualEarnings: 60_000,
    claimAge: 67,
    stopWorkAge: null,
    expected: 2345.88,
  },
  {
    label: 'high earner at FRA',
    annualEarnings: 120_000,
    claimAge: 67,
    stopWorkAge: null,
    expected: 3563.21,
  },
  {
    label: 'earnings above the SSA taxable wage base cap',
    annualEarnings: 300_000,
    claimAge: 67,
    stopWorkAge: null,
    expected: 4369.46,
  },
  {
    label: 'maximum early-claim reduction at 62',
    annualEarnings: 120_000,
    claimAge: 62,
    stopWorkAge: null,
    expected: 2494.25,
  },
  {
    label: 'delayed-credit cap at 70',
    annualEarnings: 120_000,
    claimAge: 70,
    stopWorkAge: null,
    expected: 4418.38,
  },
  {
    label: 'early retiree zeros fill the 35-year average (stop at 50)',
    annualEarnings: 120_000,
    claimAge: 67,
    stopWorkAge: 50,
    expected: 3263.21,
  },
  {
    label: 'stop-work after claim uses min(stop, claim)',
    annualEarnings: 120_000,
    claimAge: 62,
    stopWorkAge: 70,
    expected: 2494.25,
  },
]

describe('estimateSocialSecurityMonthly backend parity', () => {
  it.each(goldenRows)('$label matches backend golden cents within ±0.005', ({
    annualEarnings,
    claimAge,
    stopWorkAge,
    expected,
  }) => {
    const actual = estimateSocialSecurityMonthly(
      annualEarnings,
      claimAge,
      stopWorkAge,
    )
    expect(actual).not.toBeNull()
    expect(Math.abs((actual as number) - expected)).toBeLessThan(0.005)
  })

  it('stopping work at the assumed career start (22) zeroes the benefit', () => {
    // Backend golden: 0.0
    expect(estimateSocialSecurityMonthly(120_000, 67, 22)).toBe(0)
  })

  it('returns null for zero or missing earnings', () => {
    // Backend golden: None for both.
    expect(estimateSocialSecurityMonthly(0, 67)).toBeNull()
    expect(estimateSocialSecurityMonthly(null, 67)).toBeNull()
  })
})
