"""Ticker-to-sector ETF mapping for sector strength analysis."""

from __future__ import annotations

# Ticker -> Sector ETF mapping for individual stocks
TICKER_SECTOR_MAP: dict[str, str] = {
    # Technology
    "AAPL": "XLK",
    "MSFT": "XLK",
    "GOOGL": "XLK",
    "GOOG": "XLK",
    "META": "XLC",  # Communication Services
    "NVDA": "XLK",
    "AMD": "XLK",
    "INTC": "XLK",
    "CRM": "XLK",
    "ORCL": "XLK",
    "ADBE": "XLK",
    "CSCO": "XLK",
    "AVGO": "XLK",
    "QCOM": "XLK",
    "TXN": "XLK",
    # Financials
    "JPM": "XLF",
    "BAC": "XLF",
    "WFC": "XLF",
    "GS": "XLF",
    "MS": "XLF",
    "C": "XLF",
    "BLK": "XLF",
    "SCHW": "XLF",
    "AXP": "XLF",
    "V": "XLK",  # Actually tech/payments
    "MA": "XLK",
    # Energy
    "XOM": "XLE",
    "CVX": "XLE",
    "COP": "XLE",
    "SLB": "XLE",
    "EOG": "XLE",
    "PXD": "XLE",
    "MPC": "XLE",
    "VLO": "XLE",
    "OXY": "XLE",
    # Healthcare
    "UNH": "XLV",
    "JNJ": "XLV",
    "PFE": "XLV",
    "ABBV": "XLV",
    "MRK": "XLV",
    "LLY": "XLV",
    "TMO": "XLV",
    "ABT": "XLV",
    "DHR": "XLV",
    "BMY": "XLV",
    "AMGN": "XLV",
    # Consumer Discretionary
    "AMZN": "XLY",
    "TSLA": "XLY",
    "HD": "XLY",
    "MCD": "XLY",
    "NKE": "XLY",
    "SBUX": "XLY",
    "LOW": "XLY",
    "TJX": "XLY",
    # Consumer Staples
    "PG": "XLP",
    "KO": "XLP",
    "PEP": "XLP",
    "COST": "XLP",
    "WMT": "XLP",
    "PM": "XLP",
    "MO": "XLP",
    "CL": "XLP",
    # Industrials
    "HON": "XLI",
    "UNP": "XLI",
    "UPS": "XLI",
    "RTX": "XLI",
    "CAT": "XLI",
    "BA": "XLI",
    "DE": "XLI",
    "GE": "XLI",
    "LMT": "XLI",
    "MMM": "XLI",
    # Utilities
    "NEE": "XLU",
    "DUK": "XLU",
    "SO": "XLU",
    "D": "XLU",
    "AEP": "XLU",
    "EXC": "XLU",
    # Real Estate
    "PLD": "XLRE",
    "AMT": "XLRE",
    "CCI": "XLRE",
    "EQIX": "XLRE",
    "PSA": "XLRE",
    "SPG": "XLRE",
    # Communication Services
    "NFLX": "XLC",
    "DIS": "XLC",
    "CMCSA": "XLC",
    "VZ": "XLC",
    "T": "XLC",
    "TMUS": "XLC",
    # Materials
    "LIN": "XLB",
    "APD": "XLB",
    "SHW": "XLB",
    "ECL": "XLB",
    "FCX": "XLB",
    "NEM": "XLB",
}
