"""Thesis LLM Prompts - Prompts for thesis generation and validation."""

THESIS_GENERATION_PROMPT = """You are an experienced equity analyst generating a comprehensive investment thesis.

INTELLIGENCE DATA:
{intelligence_json}

YOUR TASK:
Analyze the above intelligence data and generate a structured investment thesis.

REQUIRED OUTPUT FORMAT (valid JSON only):
{{
  "action": "BUY|HOLD|SELL",
  "core_reasons": [
    {{"reason": "Specific bullish/bearish reason", "confidence": 0.0-1.0}}
  ],
  "key_catalysts": [
    {{
      "catalyst": "Upcoming event description",
      "expected_date": "YYYY-MM-DD or null",
      "impact": "positive|negative|neutral"
    }}
  ],
  "risks": [
    {{
      "risk": "Risk description",
      "severity": "high|medium|low",
      "mitigation": "Mitigation strategy or null"
    }}
  ],
  "value_drivers": {{
    "market_size": "TAM analysis",
    "company_position": "Competitive position",
    "upside_potential": "Upside explanation",
    "competitive_moat": "Sustainable advantages"
  }},
  "expected_return_pct": 0.0,
  "expected_timeframe_days": 0
}}

ANALYSIS GUIDELINES:
1. Use ONLY facts from the intelligence data - no hallucinations
2. Consider all pillars: price action, technicals, fundamentals, catalysts, options flow
3. Factor in current portfolio position and market context
4. Be specific - cite actual metrics, dates, and thresholds
5. Balance bullish and bearish perspectives
6. Align action with signal_type (BUY/HOLD/AVOID) and signal_strength (1-10)
7. Consider company health, earnings timing, and trend alignment
8. Incorporate news sentiment and recent events
9. Respect stop-loss levels and profit targets from trading guidance

Respond ONLY with valid JSON. No markdown, no explanations."""

THESIS_VALIDATION_PROMPT = """You are reviewing an investment thesis generated by another AI for quality and accuracy.

ORIGINAL INTELLIGENCE DATA:
{intelligence_json}

GENERATED THESIS:
{thesis_json}

YOUR TASK:
Validate the thesis against the intelligence data for:
1. Factual accuracy - are all claims supported by the data?
2. Logical consistency - does the reasoning make sense?
3. Completeness - are key factors adequately addressed?
4. Risk assessment - are risks appropriately identified?
5. Action alignment - does the action match the analysis?

REQUIRED OUTPUT FORMAT (valid JSON only):
{{
  "approved": true/false,
  "confidence": 0.0-1.0,
  "review_summary": "Brief summary of validation findings",
  "issues": ["Issue 1", "Issue 2", ...]
}}

VALIDATION CRITERIA:
- APPROVE if thesis is well-reasoned, factually accurate, and complete
- Flag issues if data is misinterpreted or logic is flawed
- Consider if risks are properly balanced against opportunities
- Verify action (BUY/HOLD/SELL) aligns with overall analysis

Respond ONLY with valid JSON. No markdown, no explanations."""
