-- Migration 007: Populate table_registry with metadata
-- Date: 2025-11-01
-- Description: Insert metadata for all 19 tables into table_registry

-- Idempotent: Uses ON CONFLICT DO UPDATE to safely re-run

-- Source/configuration tables
INSERT INTO table_registry (table_name, table_type, description)
VALUES ('source_registry', 'config', 'Data source definitions')
ON CONFLICT (table_name) DO UPDATE SET
    table_type = EXCLUDED.table_type,
    description = EXCLUDED.description;

INSERT INTO table_registry (table_name, table_type, description)
VALUES ('source_credentials', 'config', 'API keys and secrets for data sources')
ON CONFLICT (table_name) DO UPDATE SET
    table_type = EXCLUDED.table_type,
    description = EXCLUDED.description;

INSERT INTO table_registry (table_name, table_type, description)
VALUES ('endpoint_catalog', 'config', 'API endpoint definitions and field mappings')
ON CONFLICT (table_name) DO UPDATE SET
    table_type = EXCLUDED.table_type,
    description = EXCLUDED.description;

-- Portfolio tables
INSERT INTO table_registry (table_name, table_type, description)
VALUES ('portfolio_accounts', 'config', 'Portfolio account definitions')
ON CONFLICT (table_name) DO UPDATE SET
    table_type = EXCLUDED.table_type,
    description = EXCLUDED.description;

INSERT INTO table_registry (table_name, table_type, description)
VALUES ('portfolio_positions', 'config', 'Portfolio position holdings')
ON CONFLICT (table_name) DO UPDATE SET
    table_type = EXCLUDED.table_type,
    description = EXCLUDED.description;

INSERT INTO table_registry (table_name, table_type, description)
VALUES ('user_preferences', 'config', 'User risk tolerance and trade preferences')
ON CONFLICT (table_name) DO UPDATE SET
    table_type = EXCLUDED.table_type,
    description = EXCLUDED.description;

-- Cache tables
INSERT INTO table_registry (table_name, table_type, description)
VALUES ('reference_cache', 'config', 'Cached reference metadata for watchlist tickers')
ON CONFLICT (table_name) DO UPDATE SET
    table_type = EXCLUDED.table_type,
    description = EXCLUDED.description;

INSERT INTO table_registry (table_name, table_type, description)
VALUES ('price_cache', 'timeseries', 'Cached price and analytics data')
ON CONFLICT (table_name) DO UPDATE SET
    table_type = EXCLUDED.table_type,
    description = EXCLUDED.description;

-- Time series tables
INSERT INTO table_registry (table_name, table_type, description)
VALUES ('day_bars', 'timeseries', 'Historical daily OHLCV data')
ON CONFLICT (table_name) DO UPDATE SET
    table_type = EXCLUDED.table_type,
    description = EXCLUDED.description;

INSERT INTO table_registry (table_name, table_type, description)
VALUES ('minute_bars', 'timeseries', 'Intraday minute-level OHLCV data')
ON CONFLICT (table_name) DO UPDATE SET
    table_type = EXCLUDED.table_type,
    description = EXCLUDED.description;

INSERT INTO table_registry (table_name, table_type, description)
VALUES ('technical_indicators', 'timeseries', 'Cached technical indicator values')
ON CONFLICT (table_name) DO UPDATE SET
    table_type = EXCLUDED.table_type,
    description = EXCLUDED.description;

-- Watchlist tables
INSERT INTO table_registry (table_name, table_type, description)
VALUES ('watchlist_items', 'watchlist', 'User watchlist items and notes')
ON CONFLICT (table_name) DO UPDATE SET
    table_type = EXCLUDED.table_type,
    description = EXCLUDED.description;

INSERT INTO table_registry (table_name, table_type, description)
VALUES ('watchlist_snapshots', 'watchlist', 'Cached watchlist scoring snapshots')
ON CONFLICT (table_name) DO UPDATE SET
    table_type = EXCLUDED.table_type,
    description = EXCLUDED.description;

-- Agent/metadata tables
INSERT INTO table_registry (table_name, table_type, description)
VALUES ('agent_runs', 'metadata', 'Agent execution tracking')
ON CONFLICT (table_name) DO UPDATE SET
    table_type = EXCLUDED.table_type,
    description = EXCLUDED.description;

INSERT INTO table_registry (table_name, table_type, description)
VALUES ('agent_ideas', 'metadata', 'Investment ideas generated by agents')
ON CONFLICT (table_name) DO UPDATE SET
    table_type = EXCLUDED.table_type,
    description = EXCLUDED.description;

INSERT INTO table_registry (table_name, table_type, description)
VALUES ('agent_tool_calls', 'metadata', 'Tool calls made during agent execution')
ON CONFLICT (table_name) DO UPDATE SET
    table_type = EXCLUDED.table_type,
    description = EXCLUDED.description;

INSERT INTO table_registry (table_name, table_type, description)
VALUES ('validation_results', 'metadata', 'Idea validation results')
ON CONFLICT (table_name) DO UPDATE SET
    table_type = EXCLUDED.table_type,
    description = EXCLUDED.description;

INSERT INTO table_registry (table_name, table_type, description)
VALUES ('source_performance', 'metadata', 'Multi-source failover performance tracking')
ON CONFLICT (table_name) DO UPDATE SET
    table_type = EXCLUDED.table_type,
    description = EXCLUDED.description;

INSERT INTO table_registry (table_name, table_type, description)
VALUES ('idea_outcomes', 'metadata', 'Paper trading outcomes for agent ideas')
ON CONFLICT (table_name) DO UPDATE SET
    table_type = EXCLUDED.table_type,
    description = EXCLUDED.description;
