"""Shared constants for news services."""

from app.constants import MARKET_SYMBOL
from app.models.preferences import (
    ALLOWED_NEWS_LOOKBACK_HOURS,
    DEFAULT_NEWS_LOOKBACK_HOURS,
    DEFAULT_NEWS_MAX_ARTICLES,
)

__all__ = [
    "ALLOWED_LOOKBACK_HOURS",
    "ARTICLE_OVERFETCH_CAP",
    "ARTICLE_OVERFETCH_MULTIPLIER",
    "DEFAULT_MAX_ARTICLES",
    "DEFAULT_TTL_HOURS",
    "MARKET_SYMBOL",
]

# Default configuration
DEFAULT_TTL_HOURS = DEFAULT_NEWS_LOOKBACK_HOURS
DEFAULT_MAX_ARTICLES = DEFAULT_NEWS_MAX_ARTICLES
ARTICLE_OVERFETCH_MULTIPLIER = 3
ARTICLE_OVERFETCH_CAP = 45
ALLOWED_LOOKBACK_HOURS = set(ALLOWED_NEWS_LOOKBACK_HOURS)
