"""Shared constants for news services."""

from app.constants import MARKET_SYMBOL

__all__ = [
    "ALLOWED_LOOKBACK_HOURS",
    "ARTICLE_OVERFETCH_CAP",
    "ARTICLE_OVERFETCH_MULTIPLIER",
    "DEFAULT_MAX_ARTICLES",
    "DEFAULT_TTL_HOURS",
    "MARKET_SYMBOL",
]

# Default configuration
DEFAULT_TTL_HOURS = 6
DEFAULT_MAX_ARTICLES = 10
ARTICLE_OVERFETCH_MULTIPLIER = 3
ARTICLE_OVERFETCH_CAP = 45
ALLOWED_LOOKBACK_HOURS = {6, 12, 24, 48}
