"""Thesis Service - LLM-powered investment thesis generation with dual-provider validation.

This service generates structured investment theses using intelligence data from the
symbols API, leveraging both Gemini and Claude for cross-validation and quality assurance.

Key features:
- Fetches comprehensive intelligence data from internal API
- Generates thesis with Gemini, validates with Claude
- Calculates cross-validation scores based on LLM agreement
- Supports versioning and invalidation tracking
- Checks invalidation triggers based on market conditions
"""

from __future__ import annotations

import json
import uuid
from datetime import UTC, datetime
from typing import Any

import httpx
from pydantic import ValidationError

from ..agents.llm_client import DualProviderClient
from ..logging_config import get_logger
from ..models.thesis import (
    Thesis,
    ThesisAction,
    ThesisCatalyst,
    ThesisReason,
    ThesisRisk,
    ThesisStatus,
    ThesisValidation,
    ThesisValueDrivers,
    ThesisVersion,
)
from ..storage.connection import get_connection_manager

logger = get_logger(__name__)

# LLM Prompts

THESIS_GENERATION_PROMPT = """You are an experienced equity analyst generating a comprehensive investment thesis.

INTELLIGENCE DATA:
{intelligence_json}

YOUR TASK:
Analyze the above intelligence data and generate a structured investment thesis.

REQUIRED OUTPUT FORMAT (valid JSON only):
{{
  "action": "BUY|HOLD|SELL",
  "core_reasons": [
    {{"reason": "Specific bullish/bearish reason", "confidence": 0.0-1.0}}
  ],
  "key_catalysts": [
    {{
      "catalyst": "Upcoming event description",
      "expected_date": "YYYY-MM-DD or null",
      "impact": "positive|negative|neutral"
    }}
  ],
  "risks": [
    {{
      "risk": "Risk description",
      "severity": "high|medium|low",
      "mitigation": "Mitigation strategy or null"
    }}
  ],
  "value_drivers": {{
    "market_size": "TAM analysis",
    "company_position": "Competitive position",
    "upside_potential": "Upside explanation",
    "competitive_moat": "Sustainable advantages"
  }},
  "expected_return_pct": 0.0,
  "expected_timeframe_days": 0
}}

ANALYSIS GUIDELINES:
1. Use ONLY facts from the intelligence data - no hallucinations
2. Consider all pillars: price action, technicals, fundamentals, catalysts, options flow
3. Factor in current portfolio position and market context
4. Be specific - cite actual metrics, dates, and thresholds
5. Balance bullish and bearish perspectives
6. Align action with signal_type (BUY/HOLD/AVOID) and signal_strength (1-10)
7. Consider company health, earnings timing, and trend alignment
8. Incorporate news sentiment and recent events
9. Respect stop-loss levels and profit targets from trading guidance

Respond ONLY with valid JSON. No markdown, no explanations."""

THESIS_VALIDATION_PROMPT = """You are reviewing an investment thesis generated by another AI for quality and accuracy.

ORIGINAL INTELLIGENCE DATA:
{intelligence_json}

GENERATED THESIS:
{thesis_json}

YOUR TASK:
Validate the thesis against the intelligence data for:
1. Factual accuracy - are all claims supported by the data?
2. Logical consistency - does the reasoning make sense?
3. Completeness - are key factors adequately addressed?
4. Risk assessment - are risks appropriately identified?
5. Action alignment - does the action match the analysis?

REQUIRED OUTPUT FORMAT (valid JSON only):
{{
  "approved": true/false,
  "confidence": 0.0-1.0,
  "review_summary": "Brief summary of validation findings",
  "issues": ["Issue 1", "Issue 2", ...]
}}

VALIDATION CRITERIA:
- APPROVE if thesis is well-reasoned, factually accurate, and complete
- Flag issues if data is misinterpreted or logic is flawed
- Consider if risks are properly balanced against opportunities
- Verify action (BUY/HOLD/SELL) aligns with overall analysis

Respond ONLY with valid JSON. No markdown, no explanations."""


class ThesisService:
    """Service for generating and managing investment theses with dual-LLM validation."""

    def __init__(
        self,
        llm_client: DualProviderClient | None = None,
        api_base_url: str = "http://localhost:8000",
    ) -> None:
        """Initialize thesis service.

        Args:
            llm_client: Dual-provider LLM client (Gemini + Claude)
            api_base_url: Base URL for internal API calls
        """
        self._llm_client = llm_client
        self._api_base_url = api_base_url
        self._conn_mgr = get_connection_manager()

    def _ensure_llm_client(self) -> DualProviderClient:
        """Lazy-initialize LLM client."""
        if self._llm_client is None:
            self._llm_client = DualProviderClient(primary="gemini")
            logger.info("thesis_llm_client_initialized")
        return self._llm_client

    def _fetch_intelligence(self, symbol: str) -> dict[str, Any]:
        """Fetch intelligence data from internal API.

        Args:
            symbol: Stock symbol

        Returns:
            Intelligence data dictionary

        Raises:
            RuntimeError: If API call fails
        """
        url = f"{self._api_base_url}/api/symbols/{symbol}/intelligence"

        try:
            logger.info("fetching_intelligence", symbol=symbol, url=url)
            response = httpx.get(url, timeout=30.0)
            response.raise_for_status()
            data: dict[str, Any] = response.json()

            if data.get("error"):
                raise RuntimeError(f"Intelligence API returned error: {data['error']}")

            logger.info("intelligence_fetched", symbol=symbol, sections=list(data.keys()))
            return data

        except httpx.HTTPError as e:
            logger.error("intelligence_fetch_failed", symbol=symbol, error=str(e))
            raise RuntimeError(f"Failed to fetch intelligence for {symbol}: {e}") from e

    def _parse_json_response(self, content: str) -> dict[str, Any]:
        """Parse JSON from LLM response, handling markdown blocks.

        Args:
            content: LLM response content

        Returns:
            Parsed JSON dictionary

        Raises:
            ValueError: If JSON parsing fails
        """
        # Try to extract JSON from markdown blocks
        try:
            if "```json" in content:
                json_str = content.split("```json")[1].split("```")[0].strip()
            elif "```" in content:
                json_str = content.split("```")[1].split("```")[0].strip()
            elif "{" in content:
                # Find JSON object boundaries
                start = content.index("{")
                end = content.rindex("}") + 1
                json_str = content[start:end]
            else:
                raise ValueError("No JSON found in response")

            parsed: dict[str, Any] = json.loads(json_str)
            return parsed

        except (json.JSONDecodeError, ValueError, IndexError) as e:
            logger.error("json_parse_failed", content_preview=content[:500], error=str(e))
            raise ValueError(f"Failed to parse JSON from LLM response: {e}") from e

    def _generate_with_gemini(self, intelligence: dict[str, Any]) -> dict[str, Any]:
        """Generate thesis using Gemini.

        Args:
            intelligence: Intelligence data

        Returns:
            Parsed thesis JSON

        Raises:
            RuntimeError: If generation fails
        """
        llm = self._ensure_llm_client()

        # Build prompt
        intelligence_json = json.dumps(intelligence, indent=2)
        prompt = THESIS_GENERATION_PROMPT.format(intelligence_json=intelligence_json)

        logger.info("gemini_thesis_generation_started", prompt_length=len(prompt))

        try:
            response = llm.generate(
                prompt=prompt,
                system="You are an expert equity analyst. Always respond with valid JSON.",
                max_tokens=4096,
                temperature=0.7,  # Allow some creativity in reasoning
            )

            thesis_data = self._parse_json_response(response.content)
            logger.info("gemini_thesis_generated", keys=list(thesis_data.keys()))
            return thesis_data

        except Exception as e:
            logger.error("gemini_thesis_generation_failed", error=str(e))
            raise RuntimeError(f"Gemini thesis generation failed: {e}") from e

    def _validate_with_claude(
        self, intelligence: dict[str, Any], thesis_data: dict[str, Any]
    ) -> ThesisValidation:
        """Validate thesis using Claude.

        Args:
            intelligence: Original intelligence data
            thesis_data: Generated thesis data

        Returns:
            ThesisValidation object
        """
        from ..agents.clients.agent_hub_client import AgentHubAPIClient  # noqa: PLC0415

        try:
            claude = AgentHubAPIClient(model="claude-sonnet-4-5-20250514")

            # Build validation prompt
            intelligence_json = json.dumps(intelligence, indent=2)
            thesis_json = json.dumps(thesis_data, indent=2)
            prompt = THESIS_VALIDATION_PROMPT.format(
                intelligence_json=intelligence_json, thesis_json=thesis_json
            )

            logger.info("claude_validation_started", prompt_length=len(prompt))

            response = claude.generate(
                prompt=prompt,
                system="You are a thorough investment thesis reviewer. Always respond with valid JSON.",
                max_tokens=2048,
                temperature=0.3,  # Lower temperature for consistent reviews
            )

            validation_data = self._parse_json_response(response.content)

            logger.info(
                "claude_validation_completed",
                approved=validation_data.get("approved"),
                confidence=validation_data.get("confidence"),
            )

            return ThesisValidation(
                provider="claude",
                approved=validation_data.get("approved", False),
                confidence=validation_data.get("confidence", 0.0),
                review_summary=validation_data.get("review_summary", ""),
                issues=validation_data.get("issues", []),
            )

        except Exception as e:
            logger.error("claude_validation_failed", error=str(e))
            # Return failed validation instead of raising
            return ThesisValidation(
                provider="claude",
                approved=False,
                confidence=0.0,
                review_summary=f"Validation failed: {e}",
                issues=["Validation process encountered an error"],
            )

    def _calculate_cross_validation_score(self, claude_validation: ThesisValidation) -> float:
        """Calculate cross-validation score based on Claude's validation.

        Args:
            claude_validation: Validation result from Claude

        Returns:
            Score between 0.0 and 1.0
        """
        if not claude_validation.approved:
            # Penalize based on number of issues
            issue_count = len(claude_validation.issues)
            penalty = min(0.3, issue_count * 0.1)
            return max(0.0, claude_validation.confidence - penalty)

        # Approved - return confidence directly
        return claude_validation.confidence

    def _save_thesis(self, thesis: Thesis) -> None:
        """Save thesis to database.

        Args:
            thesis: Thesis object to save
        """
        with self._conn_mgr.connection() as conn:
            # Serialize nested objects to JSON
            core_reasons_json = json.dumps([r.model_dump() for r in thesis.core_reasons])
            key_catalysts_json = json.dumps([c.model_dump() for c in thesis.key_catalysts])
            risks_json = json.dumps([r.model_dump() for r in thesis.risks])
            value_drivers_json = (
                json.dumps(thesis.value_drivers.model_dump()) if thesis.value_drivers else None
            )
            claude_validation_json = (
                json.dumps(thesis.claude_validation.model_dump())
                if thesis.claude_validation
                else None
            )
            gemini_validation_json = (
                json.dumps(thesis.gemini_validation.model_dump())
                if thesis.gemini_validation
                else None
            )

            conn.execute(
                """
                INSERT INTO watchlist_thesis (
                    id, symbol, version, status, action,
                    core_reasons, key_catalysts, risks, value_drivers,
                    expected_return_pct, expected_timeframe_days,
                    claude_validation, gemini_validation, cross_validation_score,
                    invalidation_reason, invalidated_at,
                    created_at, updated_at
                ) VALUES (
                    %s, %s, %s, %s, %s, %s::jsonb, %s::jsonb, %s::jsonb, %s::jsonb, %s, %s, %s::jsonb, %s::jsonb, %s, %s, %s, %s, %s
                )
                ON CONFLICT (symbol) DO UPDATE SET
                    version = EXCLUDED.version,
                    status = EXCLUDED.status,
                    action = EXCLUDED.action,
                    core_reasons = EXCLUDED.core_reasons,
                    key_catalysts = EXCLUDED.key_catalysts,
                    risks = EXCLUDED.risks,
                    value_drivers = EXCLUDED.value_drivers,
                    expected_return_pct = EXCLUDED.expected_return_pct,
                    expected_timeframe_days = EXCLUDED.expected_timeframe_days,
                    claude_validation = EXCLUDED.claude_validation,
                    gemini_validation = EXCLUDED.gemini_validation,
                    cross_validation_score = EXCLUDED.cross_validation_score,
                    invalidation_reason = EXCLUDED.invalidation_reason,
                    invalidated_at = EXCLUDED.invalidated_at,
                    updated_at = EXCLUDED.updated_at
                """,
                (
                    thesis.id,
                    thesis.symbol,
                    thesis.version,
                    thesis.status.value,
                    thesis.action.value,
                    core_reasons_json,
                    key_catalysts_json,
                    risks_json,
                    value_drivers_json,
                    thesis.expected_return_pct,
                    thesis.expected_timeframe_days,
                    claude_validation_json,
                    gemini_validation_json,
                    thesis.cross_validation_score,
                    thesis.invalidation_reason,
                    thesis.invalidated_at,
                    thesis.created_at,
                    thesis.updated_at,
                ),
            )
            conn.commit()

        logger.info(
            "thesis_saved",
            thesis_id=thesis.id,
            symbol=thesis.symbol,
            version=thesis.version,
            status=thesis.status.value,
        )

    def _save_version(self, thesis: Thesis, change_reason: str) -> None:
        """Save thesis version to history.

        Args:
            thesis: Thesis object
            change_reason: Reason for version change
        """
        version_id = str(uuid.uuid4())

        with self._conn_mgr.connection() as conn:
            conn.execute(
                """
                INSERT INTO thesis_versions (
                    id, thesis_id, version, snapshot, change_reason, created_at
                ) VALUES (%s, %s, %s, %s, %s, %s)
                """,
                (
                    version_id,
                    thesis.id,
                    thesis.version,
                    json.dumps(thesis.model_dump()),
                    change_reason,
                    datetime.now(UTC).isoformat(),
                ),
            )
            conn.commit()

        logger.info(
            "thesis_version_saved",
            version_id=version_id,
            thesis_id=thesis.id,
            version=thesis.version,
        )

    def generate_thesis(self, symbol: str, force: bool = False) -> Thesis:
        """Generate investment thesis for symbol.

        Workflow:
        1. Fetch intelligence from internal API
        2. Generate thesis with Gemini
        3. Validate with Claude
        4. Calculate cross-validation score
        5. Save to database with version history

        Args:
            symbol: Stock symbol
            force: Force regeneration even if recent thesis exists

        Returns:
            Generated Thesis object

        Raises:
            RuntimeError: If generation fails
        """
        symbol = symbol.upper()

        # Check for existing active thesis
        if not force:
            existing = self.get_thesis(symbol)
            if existing and existing.status == ThesisStatus.ACTIVE:
                # Check if thesis is recent (< 24 hours old)
                created = datetime.fromisoformat(existing.created_at)
                age_hours = (datetime.now(UTC) - created).total_seconds() / 3600
                if age_hours < 24:
                    logger.info(
                        "thesis_already_recent",
                        symbol=symbol,
                        thesis_id=existing.id,
                        age_hours=age_hours,
                    )
                    return existing

        logger.info("thesis_generation_started", symbol=symbol, force=force)

        try:
            # Step 1: Fetch intelligence
            intelligence = self._fetch_intelligence(symbol)

            # Step 2: Generate with Gemini
            thesis_data = self._generate_with_gemini(intelligence)

            # Step 3: Validate with Claude
            claude_validation = self._validate_with_claude(intelligence, thesis_data)

            # Step 4: Calculate cross-validation score
            cross_val_score = self._calculate_cross_validation_score(claude_validation)

            # Step 5: Build Thesis object
            now = datetime.now(UTC).isoformat()

            # Determine version (increment if existing)
            existing = self.get_thesis(symbol)
            version = (existing.version + 1) if existing else 1

            # Parse thesis components
            try:
                core_reasons = [ThesisReason(**r) for r in thesis_data.get("core_reasons", [])]
            except ValidationError as e:
                logger.warning("core_reasons_parse_failed", error=str(e))
                core_reasons = []

            try:
                key_catalysts = [ThesisCatalyst(**c) for c in thesis_data.get("key_catalysts", [])]
            except ValidationError as e:
                logger.warning("key_catalysts_parse_failed", error=str(e))
                key_catalysts = []

            try:
                risks = [ThesisRisk(**r) for r in thesis_data.get("risks", [])]
            except ValidationError as e:
                logger.warning("risks_parse_failed", error=str(e))
                risks = []

            value_drivers = None
            if thesis_data.get("value_drivers"):
                try:
                    value_drivers = ThesisValueDrivers(**thesis_data["value_drivers"])
                except ValidationError as e:
                    logger.warning("value_drivers_parse_failed", error=str(e))

            thesis = Thesis(
                id=str(uuid.uuid4()),
                symbol=symbol,
                version=version,
                status=ThesisStatus.ACTIVE,
                action=ThesisAction(thesis_data.get("action", "HOLD")),
                core_reasons=core_reasons,
                key_catalysts=key_catalysts,
                risks=risks,
                value_drivers=value_drivers,
                expected_return_pct=thesis_data.get("expected_return_pct"),
                expected_timeframe_days=thesis_data.get("expected_timeframe_days"),
                claude_validation=claude_validation,
                gemini_validation=None,  # Not implementing Gemini validation of Claude for now
                cross_validation_score=cross_val_score,
                invalidation_reason=None,
                invalidated_at=None,
                created_at=now,
                updated_at=now,
            )

            # Step 6: Save to database
            self._save_thesis(thesis)
            self._save_version(thesis, "Generated new thesis")

            logger.info(
                "thesis_generation_completed",
                thesis_id=thesis.id,
                symbol=symbol,
                version=version,
                cross_val_score=cross_val_score,
                claude_approved=claude_validation.approved,
            )

            return thesis

        except Exception as e:
            logger.error("thesis_generation_failed", symbol=symbol, error=str(e))
            raise RuntimeError(f"Failed to generate thesis for {symbol}: {e}") from e

    def get_thesis(self, symbol: str) -> Thesis | None:
        """Retrieve current active thesis for symbol.

        Args:
            symbol: Stock symbol

        Returns:
            Thesis object or None if not found
        """
        symbol = symbol.upper()

        with self._conn_mgr.connection() as conn:
            result = conn.execute(
                """
                SELECT
                    id, symbol, version, status, action,
                    core_reasons, key_catalysts, risks, value_drivers,
                    expected_return_pct, expected_timeframe_days,
                    claude_validation, gemini_validation, cross_validation_score,
                    invalidation_reason, invalidated_at,
                    created_at, updated_at
                FROM watchlist_thesis
                WHERE UPPER(symbol) = UPPER(%s)
                ORDER BY created_at DESC
                LIMIT 1
                """,
                (symbol,),
            )
            row = result.fetchone()

            if not row:
                return None

            # Parse row into Thesis object
            return self._row_to_thesis(row)

    def get_thesis_versions(self, symbol: str, limit: int = 10) -> list[ThesisVersion]:
        """Retrieve version history for symbol.

        Args:
            symbol: Stock symbol
            limit: Maximum number of versions to return

        Returns:
            List of ThesisVersion objects (newest first)
        """
        symbol = symbol.upper()

        with self._conn_mgr.connection() as conn:
            result = conn.execute(
                """
                SELECT tv.id, tv.thesis_id, tv.version, tv.snapshot, tv.change_reason, tv.created_at
                FROM thesis_versions tv
                JOIN watchlist_thesis t ON tv.thesis_id = t.id
                WHERE UPPER(t.symbol) = UPPER(%s)
                ORDER BY tv.created_at DESC
                LIMIT %s
                """,
                (symbol, limit),
            )
            rows = result.fetchall()

            versions = []
            for row in rows:
                # Parse snapshot JSON
                snapshot_str = row[3]
                if isinstance(snapshot_str, str):
                    snapshot = json.loads(snapshot_str)
                else:
                    snapshot = snapshot_str

                # Handle datetime conversion
                created_at_val = row[5]
                if created_at_val is not None and hasattr(created_at_val, "isoformat"):
                    created_at_str = created_at_val.isoformat()
                else:
                    created_at_str = str(created_at_val) if created_at_val else ""

                versions.append(
                    ThesisVersion(
                        id=str(row[0]),
                        thesis_id=str(row[1]),
                        version=int(row[2]) if row[2] is not None else 0,
                        snapshot=snapshot,
                        change_reason=str(row[4]) if row[4] else "",
                        created_at=created_at_str,
                    )
                )

            return versions

    def invalidate_thesis(self, symbol: str, reason: str) -> Thesis | None:
        """Mark thesis as invalidated and increment version.

        Args:
            symbol: Stock symbol
            reason: Invalidation reason

        Returns:
            Updated Thesis object or None if not found
        """
        symbol = symbol.upper()
        thesis = self.get_thesis(symbol)

        if not thesis:
            logger.warning("thesis_not_found_for_invalidation", symbol=symbol)
            return None

        # Update status
        now = datetime.now(UTC).isoformat()
        thesis.status = ThesisStatus.INVALIDATED
        thesis.invalidation_reason = reason
        thesis.invalidated_at = now
        thesis.updated_at = now
        thesis.version += 1

        # Save updates
        self._save_thesis(thesis)
        self._save_version(thesis, f"Invalidated: {reason}")

        logger.info(
            "thesis_invalidated",
            thesis_id=thesis.id,
            symbol=symbol,
            version=thesis.version,
            reason=reason,
        )

        return thesis

    def check_invalidation_triggers(self, symbol: str) -> list[str]:
        """Check if any invalidation triggers are met.

        Invalidation triggers:
        - Signal type changed from BUY to AVOID (or vice versa)
        - Signal strength dropped by ≥3 points
        - Cross-validation score < 0.5
        - Stop-loss breach detected
        - Major news event (sentiment shift > 0.3)

        Args:
            symbol: Stock symbol

        Returns:
            List of triggered reasons (empty if none)
        """
        symbol = symbol.upper()
        triggers = []

        try:
            # Fetch current intelligence
            intelligence = self._fetch_intelligence(symbol)

            # Get current thesis
            thesis = self.get_thesis(symbol)
            if not thesis or thesis.status != ThesisStatus.ACTIVE:
                return []

            # Trigger 1: Signal type changed significantly
            scores = intelligence.get("scores") or {}
            current_signal = scores.get("signal_type")
            thesis_action = thesis.action.value

            if current_signal == "AVOID" and thesis_action == "BUY":
                triggers.append("Signal changed from BUY to AVOID")
            elif current_signal == "BUY" and thesis_action == "SELL":
                triggers.append("Signal changed from SELL to BUY")

            # Trigger 2: Signal strength dropped significantly
            # NOTE: We don't store original signal strength in thesis, so skip this check.
            # Future enhancement: Store signal_strength_at_creation in thesis metadata
            _ = scores.get("signal_strength")  # Placeholder for future implementation

            # Trigger 3: Low cross-validation score
            if thesis.cross_validation_score and thesis.cross_validation_score < 0.5:
                triggers.append(f"Low cross-validation score: {thesis.cross_validation_score:.2f}")

            # Trigger 4: News sentiment shift
            news = intelligence.get("news") or {}
            sentiment_score = news.get("sentiment_score")
            if sentiment_score is not None:
                # Check for major negative shift if thesis is BUY
                if thesis_action == "BUY" and sentiment_score < -0.3:
                    triggers.append(f"Negative news sentiment: {sentiment_score:.2f}")
                # Check for major positive shift if thesis is SELL
                elif thesis_action == "SELL" and sentiment_score > 0.3:
                    triggers.append(f"Positive news sentiment: {sentiment_score:.2f}")

            logger.info(
                "invalidation_triggers_checked",
                symbol=symbol,
                triggers_count=len(triggers),
                triggers=triggers,
            )

            return triggers

        except Exception as e:
            logger.error("invalidation_trigger_check_failed", symbol=symbol, error=str(e))
            return []

    def _row_to_thesis(self, row: tuple[Any, ...]) -> Thesis:
        """Convert database row to Thesis object.

        Args:
            row: Database row tuple

        Returns:
            Thesis object
        """
        # Parse JSONB fields
        core_reasons_raw = row[5]
        if isinstance(core_reasons_raw, str):
            core_reasons_raw = json.loads(core_reasons_raw)
        core_reasons = [ThesisReason(**r) for r in (core_reasons_raw or [])]

        key_catalysts_raw = row[6]
        if isinstance(key_catalysts_raw, str):
            key_catalysts_raw = json.loads(key_catalysts_raw)
        key_catalysts = [ThesisCatalyst(**c) for c in (key_catalysts_raw or [])]

        risks_raw = row[7]
        if isinstance(risks_raw, str):
            risks_raw = json.loads(risks_raw)
        risks = [ThesisRisk(**r) for r in (risks_raw or [])]

        value_drivers_raw = row[8]
        if value_drivers_raw:
            if isinstance(value_drivers_raw, str):
                value_drivers_raw = json.loads(value_drivers_raw)
            value_drivers = ThesisValueDrivers(**value_drivers_raw)
        else:
            value_drivers = None

        claude_validation_raw = row[11]
        if claude_validation_raw:
            if isinstance(claude_validation_raw, str):
                claude_validation_raw = json.loads(claude_validation_raw)
            claude_validation = ThesisValidation(**claude_validation_raw)
        else:
            claude_validation = None

        gemini_validation_raw = row[12]
        if gemini_validation_raw:
            if isinstance(gemini_validation_raw, str):
                gemini_validation_raw = json.loads(gemini_validation_raw)
            gemini_validation = ThesisValidation(**gemini_validation_raw)
        else:
            gemini_validation = None

        # Handle datetime conversion
        created_at = row[16]
        if hasattr(created_at, "isoformat"):
            created_at = created_at.isoformat()

        updated_at = row[17]
        if hasattr(updated_at, "isoformat"):
            updated_at = updated_at.isoformat()

        invalidated_at = row[15]
        if invalidated_at and hasattr(invalidated_at, "isoformat"):
            invalidated_at = invalidated_at.isoformat()

        return Thesis(
            id=row[0],
            symbol=row[1],
            version=row[2],
            status=ThesisStatus(row[3]),
            action=ThesisAction(row[4]),
            core_reasons=core_reasons,
            key_catalysts=key_catalysts,
            risks=risks,
            value_drivers=value_drivers,
            expected_return_pct=row[9],
            expected_timeframe_days=row[10],
            claude_validation=claude_validation,
            gemini_validation=gemini_validation,
            cross_validation_score=row[13],
            invalidation_reason=row[14],
            invalidated_at=invalidated_at,
            created_at=created_at,
            updated_at=updated_at,
        )
