"""Data models for dynamic strategy generation system.

This module defines the data structures used across the strategy generation pipeline.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date, datetime
from decimal import Decimal
from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator


@dataclass
class ResearchInsights:
    """Structured research summary for strategy generation.

    Aggregates market research from all available sources (news, fundamentals,
    technical, macro, sector) into a unified structure for LLM analysis.

    Confidence scores (0-1) indicate data quality and completeness.
    """

    symbol: str
    as_of_date: date

    # News Intelligence (30-day rolling)
    news_sentiment_trend: Literal["improving", "stable", "deteriorating"]
    news_sentiment_score: float  # -1.0 to +1.0 (current)
    news_sentiment_7d_avg: float  # 7-day rolling average
    news_sentiment_30d_avg: float  # 30-day rolling average
    material_events: list[str]  # ["earnings_beat", "product_launch"]
    news_volume: int  # Article count in 30 days
    news_confidence: float  # 0-1 (based on article count + source quality)

    # Fundamental Analysis
    company_health: Literal["EXCELLENT", "GOOD", "WEAK"]
    fundamental_score: int  # 0-100 (4-pillar composite)
    valuation_tier: Literal["undervalued", "fair", "overvalued"]
    growth_tier: Literal["accelerating", "stable", "slowing"]
    profitability_tier: Literal["excellent", "good", "weak"]
    debt_tier: Literal["low", "moderate", "high"]
    analyst_consensus: float  # 1.0-5.0 (1=strong buy, 5=sell)
    fundamental_confidence: float  # 0-1 (based on data completeness)

    # Technical Analysis
    trend_strength: Literal["strong_up", "weak_up", "neutral", "weak_down", "strong_down"]
    trend_duration_days: int  # How long current trend has lasted
    momentum_rating: Literal["accelerating", "steady", "decelerating"]
    volume_profile: Literal["increasing", "stable", "decreasing"]
    rsi_zone: Literal["oversold", "healthy", "overbought"]
    price_vs_ma: dict[str, float]  # {"20d": 1.05, "50d": 1.08, "200d": 1.12}
    technical_confidence: float  # 0-1 (always 1.0 if we have 252 days data)

    # Macro Context
    market_regime: Literal["bull", "bear", "range", "volatile"]
    fear_greed_score: int  # 0-100
    fear_greed_classification: Literal["extreme_fear", "fear", "neutral", "greed", "extreme_greed"]
    sector_rotation_phase: Literal["early_cycle", "mid_cycle", "late_cycle", "recession"]

    # Sector Relative Strength
    sector: str  # e.g., "Technology", "Healthcare"
    sector_momentum: Literal["leading", "in_line", "lagging"]
    sector_vs_spy_30d: float  # +5.2 = outperforming by 5.2%
    sector_rotation_signal: Literal["rotate_in", "hold", "rotate_out"]

    # Composite Assessment
    overall_confidence: float  # 0-1 (weighted average of source confidences)
    research_quality: Literal["high", "medium", "low"]
    last_updated: datetime = field(default_factory=datetime.now)


class StrategyParameters(BaseModel):
    """Strategy configuration parameters generated by LLM agent."""

    # Confirmation weights (must sum to 1.0)
    weight_price_trend: float = Field(ge=0.0, le=1.0)
    weight_rsi_health: float = Field(ge=0.0, le=1.0)
    weight_momentum: float = Field(ge=0.0, le=1.0)
    weight_volume: float = Field(ge=0.0, le=1.0)
    weight_fundamentals: float = Field(ge=0.0, le=1.0)
    weight_news_sentiment: float = Field(ge=0.0, le=1.0)
    weight_sector_alignment: float = Field(ge=0.0, le=1.0)

    # Entry thresholds
    min_confirmations: int = Field(ge=3, le=8, default=6)
    min_weighted_score: float = Field(ge=0.5, le=1.0, default=0.65)

    # Risk management
    stop_loss_atr_multiplier: Decimal = Field(gt=0, default=Decimal("2.0"))
    max_holding_days: int = Field(gt=0, default=60)
    position_sizing_method: Literal["fixed_dollars", "fixed_shares"] = "fixed_dollars"
    position_size_value: Decimal = Field(gt=0, default=Decimal("10000.00"))

    # Strategy-specific overrides (technical thresholds)
    rsi_oversold_threshold: int = Field(ge=0, le=50, default=30)
    rsi_overbought_threshold: int = Field(ge=50, le=100, default=70)
    volume_multiplier_threshold: float = Field(gt=0, default=0.7)
    news_sentiment_threshold: float = Field(ge=-1.0, le=1.0, default=0.2)

    @field_validator("weight_price_trend")
    @classmethod
    def validate_weights_sum(cls, v: float, info) -> float:  # type: ignore
        """Ensure all confirmation weights sum to 1.0."""
        # Only validate when all fields are set (at end of initialization)
        if info.data.get("weight_sector_alignment") is None:
            return v

        weights = [
            info.data.get("weight_price_trend", 0.0),
            info.data.get("weight_rsi_health", 0.0),
            info.data.get("weight_momentum", 0.0),
            info.data.get("weight_volume", 0.0),
            info.data.get("weight_fundamentals", 0.0),
            info.data.get("weight_news_sentiment", 0.0),
            info.data.get("weight_sector_alignment", 0.0),
        ]
        total = sum(weights)

        if not 0.99 <= total <= 1.01:
            raise ValueError(f"Weights must sum to 1.0, got {total:.4f}")

        return v


class ExpectedCharacteristics(BaseModel):
    """Expected strategy performance characteristics."""

    avg_holding_period_days: int = Field(gt=0)
    expected_win_rate: float = Field(ge=0.0, le=1.0)
    expected_sharpe: float = Field(ge=0.0)
    risk_level: Literal["low", "medium-low", "medium", "medium-high", "high"]


class StrategyGenerationResult(BaseModel):
    """Agent output from strategy generation."""

    strategy_type: Literal["momentum", "value", "event", "reversal", "defensive", "no_strategy"]
    reasoning: str = Field(min_length=50, max_length=500)
    confidence: float = Field(ge=0.0, le=1.0)

    parameters: StrategyParameters
    expected_characteristics: ExpectedCharacteristics


class OptimizedStrategyConfig(BaseModel):
    """Optimized strategy configuration after backtesting."""

    strategy_type: str
    parameters: StrategyParameters
    optimization_metrics: list[dict[str, Any]]  # Walk-forward backtest results
    confidence: float = Field(ge=0.0, le=1.0)
    avg_sharpe: float
    max_drawdown: float
    avg_win_rate: float


class StrategyDefinition(BaseModel):
    """Database model for stored strategies."""

    id: str  # UUID
    name: str
    symbol: str
    strategy_type: str

    # Configuration
    parameters: dict[str, Any]  # StrategyParameters as JSON
    research_summary: dict[str, Any]  # ResearchInsights as JSON
    generation_reasoning: str

    # Performance metrics
    backtest_metrics: list[dict[str, Any]]  # Walk-forward validation results
    expected_sharpe: Decimal | None
    expected_win_rate: Decimal | None
    expected_max_drawdown: Decimal | None

    # Metadata
    created_by: str
    created_at: datetime
    version: int

    # Status
    status: Literal["testing", "active", "archived"]
    activation_date: datetime | None = None
    archive_date: datetime | None = None
    archive_reason: str | None = None

    # Live performance
    live_trades_count: int = 0
    live_win_rate: Decimal | None = None
    live_sharpe_ratio: Decimal | None = None
    last_used_at: datetime | None = None
    live_metrics_updated_at: datetime | None = None
