"use client";

import { useState } from "react";
import { Brain, Plus, Sparkles } from "lucide-react";
import { PageHeader } from "@/components/shared/PageHeader";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useStrategies, useGenerateStrategiesBatch } from "@/lib/hooks/useStrategies";
import { StrategiesTable } from "@/components/strategies/StrategiesTable";
import { StrategyDetailModal } from "@/components/strategies/StrategyDetailModal";

import { PageContainer } from "@/components/shared/PageContainer";

export default function StrategiesPage() {
  const [selectedStrategyId, setSelectedStrategyId] = useState<string | null>(null);
  const [statusFilter, setStatusFilter] = useState<"all" | "testing" | "active" | "archived">(
    "all"
  );

  const { data, isLoading } = useStrategies(
    statusFilter === "all" ? undefined : { status: statusFilter }
  );
  const generateBatch = useGenerateStrategiesBatch();

  const strategies = data?.strategies || [];

  // Calculate summary stats
  const totalStrategies = strategies.length;
  const activeCount = strategies.filter((s) => s.status === "active").length;
  const testingCount = strategies.filter((s) => s.status === "testing").length;
  const avgSharpe =
    strategies.length > 0
      ? strategies.reduce((sum, s) => sum + (s.expected_sharpe || 0), 0) / strategies.length
      : 0;

  return (
    <PageContainer className="space-y-10 py-10">
      {/* Page Header */}
      <PageHeader
        title="AI Strategies"
        description="Research-backed trading strategies generated by autonomous agents"
        size="md"
        actions={
          <Button
            onClick={() => generateBatch.mutate({ top_n: 20 })}
            disabled={generateBatch.isPending}
          >
            <Sparkles className="mr-2 h-4 w-4" />
            {generateBatch.isPending ? "Generating..." : "Generate Strategies"}
          </Button>
        }
      />

      {/* Summary Cards */}
      <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-4">
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-text-muted">Total Strategies</p>
                <p className="text-3xl font-bold">{totalStrategies}</p>
              </div>
              <Brain className="h-8 w-8 text-primary" />
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-text-muted">Active</p>
                <p className="text-3xl font-bold text-green-600">{activeCount}</p>
              </div>
              <Badge variant="default" className="bg-green-500">
                Live
              </Badge>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-text-muted">Testing</p>
                <p className="text-3xl font-bold text-yellow-600">{testingCount}</p>
              </div>
              <Badge variant="outline" className="border-yellow-500 text-yellow-600">
                Paper
              </Badge>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-text-muted">Avg Expected Sharpe</p>
                <p className="text-3xl font-bold">{avgSharpe.toFixed(2)}</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Strategies Table with Tabs */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle>Generated Strategies</CardTitle>
            <Tabs
              value={statusFilter}
              onValueChange={(v) =>
                setStatusFilter(v as "all" | "testing" | "active" | "archived")
              }
            >
              <TabsList>
                <TabsTrigger value="all">All</TabsTrigger>
                <TabsTrigger value="testing">Testing</TabsTrigger>
                <TabsTrigger value="active">Active</TabsTrigger>
                <TabsTrigger value="archived">Archived</TabsTrigger>
              </TabsList>
            </Tabs>
          </div>
        </CardHeader>
        <CardContent>
          <StrategiesTable
            strategies={strategies}
            isLoading={isLoading}
            onSelectStrategy={setSelectedStrategyId}
          />
        </CardContent>
      </Card>

      {/* Strategy Detail Modal */}
      <StrategyDetailModal
        strategyId={selectedStrategyId}
        open={!!selectedStrategyId}
        onOpenChange={(open) => !open && setSelectedStrategyId(null)}
      />
    </PageContainer>
  );
}
