'use client'

import { Brain, Sparkles } from 'lucide-react'
import { useSearchParams } from 'next/navigation'
import { Suspense, useEffect, useState } from 'react'
import { PageContainer } from '@/components/shared/PageContainer'
import { PageHeader } from '@/components/shared/PageHeader'
import { StrategiesTable } from '@/components/strategies/StrategiesTable'
import { StrategyDetailModal } from '@/components/strategies/StrategyDetailModal'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import {
  useGenerateStrategiesBatch,
  useStrategies,
} from '@/lib/hooks/useStrategies'

function StrategiesPageContent() {
  const searchParams = useSearchParams()
  const [selectedStrategyId, setSelectedStrategyId] = useState<string | null>(
    null,
  )
  const [statusFilter, setStatusFilter] = useState<
    'all' | 'testing' | 'active' | 'archived'
  >('all')

  const { data, isLoading } = useStrategies(
    statusFilter === 'all' ? undefined : { status: statusFilter },
  )
  const generateBatch = useGenerateStrategiesBatch()

  useEffect(() => {
    const idParam = searchParams?.get('id')
    const strategies = data?.strategies || []

    if (idParam && strategies.length > 0 && !selectedStrategyId) {
      if (idParam === 'first' || idParam === 'latest') {
        setSelectedStrategyId(strategies[0].id)
      } else {
        const targetStrategy = strategies.find((s) => s.id === idParam)
        if (targetStrategy) {
          setSelectedStrategyId(idParam)
        }
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [searchParams, data, selectedStrategyId])

  const strategies = data?.strategies || []
  const totalStrategies = strategies.length
  const activeCount = strategies.filter((s) => s.status === 'active').length
  const testingCount = strategies.filter((s) => s.status === 'testing').length
  const avgSharpe =
    strategies.length > 0
      ? strategies.reduce((sum, s) => sum + (s.expectedSharpe || 0), 0) /
        strategies.length
      : 0

  return (
    <PageContainer className="space-y-10 py-10">
      <PageHeader
        title="AI Strategies"
        description="Research-backed trading strategies generated by autonomous agents"
        size="md"
        actions={
          <Button
            onClick={() => generateBatch.mutate({ topN: 20 })}
            disabled={generateBatch.isPending}
          >
            <Sparkles className="mr-2 h-4 w-4" />
            {generateBatch.isPending ? 'Generating...' : 'Generate Strategies'}
          </Button>
        }
      />

      <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-4">
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-text-muted">
                  Total Strategies
                </p>
                <p className="text-3xl font-bold">{totalStrategies}</p>
              </div>
              <Brain className="h-8 w-8 text-primary" />
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-text-muted">Active</p>
                <p className="text-3xl font-bold text-gain">{activeCount}</p>
              </div>
              <Badge variant="default" className="bg-gain">
                Live
              </Badge>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-text-muted">Testing</p>
                <p className="text-3xl font-bold text-warning">
                  {testingCount}
                </p>
              </div>
              <Badge variant="outline" className="border-warning text-warning">
                Paper
              </Badge>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-text-muted">
                  Avg Expected Sharpe
                </p>
                <p className="text-3xl font-bold">{avgSharpe.toFixed(2)}</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle>Generated Strategies</CardTitle>
            <Tabs
              value={statusFilter}
              onValueChange={(value) =>
                setStatusFilter(
                  value as 'all' | 'testing' | 'active' | 'archived',
                )
              }
            >
              <TabsList>
                <TabsTrigger value="all">All</TabsTrigger>
                <TabsTrigger value="testing">Testing</TabsTrigger>
                <TabsTrigger value="active">Active</TabsTrigger>
                <TabsTrigger value="archived">Archived</TabsTrigger>
              </TabsList>
            </Tabs>
          </div>
        </CardHeader>
        <CardContent>
          <StrategiesTable
            strategies={strategies}
            isLoading={isLoading}
            onSelectStrategy={setSelectedStrategyId}
          />
        </CardContent>
      </Card>

      <StrategyDetailModal
        strategyId={selectedStrategyId}
        open={!!selectedStrategyId}
        onOpenChange={(open) => !open && setSelectedStrategyId(null)}
      />
    </PageContainer>
  )
}

export function StrategiesPageClient() {
  return (
    <Suspense fallback={<div className="p-10">Loading...</div>}>
      <StrategiesPageContent />
    </Suspense>
  )
}
