"""supersede non unit basis price findings

Revision ID: c1d2e3f4a5b6
Revises: b7d4f0a9c2e1
Create Date: 2026-06-19 00:00:00.000000

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "c1d2e3f4a5b6"
down_revision: str | Sequence[str] | None = "b7d4f0a9c2e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        UPDATE household_price_findings
        SET status = 'superseded',
            updated_at = CURRENT_TIMESTAMP,
            payload = jsonb_set(
                COALESCE(payload, '{}'::jsonb),
                '{superseded_reason}',
                to_jsonb('missing normalized unit-basis comparison metadata'::text),
                true
            )
        WHERE status = 'open'
          AND (
              kind = 'savings_rollup'
              OR (
                  kind = 'cheaper_elsewhere'
                  AND (
                      payload->>'unit_label' IS NULL
                      OR payload->>'comparison_quantity' IS NULL
                      OR payload->>'household_equivalent_total' IS NULL
                      OR payload->>'vendor_equivalent_total' IS NULL
                  )
              )
          )
        """
    )


def downgrade() -> None:
    # Data cleanup is intentionally not reversible; superseded findings are
    # regenerated by the next price-check run.
    return None
