"""LLM Strategy Reviewer - Post-analysis prompts and guardrails.

Zero-cost LLM review of trading signals using Claude/Gemini CLI tools.
Acts as second opinion on strategy recommendations, NOT primary decision maker.

Section 1.3: Fee awareness added to system prompt.
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING, Any, TypedDict

from app.rules import get_rules

if TYPE_CHECKING:
    from app.storage.facade import PortfolioStorage

from app.agents.performance_metrics import get_full_performance_prompt_section


class GuardrailsDict(TypedDict):
    """Type definition for guardrails configuration."""

    max_tokens: int
    temperature: float
    forbidden_patterns: list[str]
    required_patterns: list[str]


def _get_fee_warning() -> str:
    """Generate fee warning section from rules engine."""
    rules = get_rules()
    fees = rules.fees

    # Calculate round-trip cost
    round_trip_pct = (fees.commission_pct * 100 * 2) + (fees.slippage_bps / 100 * 2)

    return f"""
TRADING COSTS (consider these in all recommendations):
- Commission: {fees.commission_pct * 100:.2f}% per trade
- Slippage: ~{fees.slippage_bps / 100:.2f}% on market orders
- Round-trip cost: ~{round_trip_pct:.2f}%
- Minimum profitable position: ${500}

Excessive trading erodes returns. Focus on high-conviction opportunities.
"""


def get_system_prompt(storage: PortfolioStorage) -> str:
    """Get system prompt for Strategy Reviewer with performance metrics.

    Args:
        storage: PortfolioStorage instance for fetching performance metrics

    Returns:
        Formatted system prompt string
    """
    # Get performance context
    try:
        perf_context = get_full_performance_prompt_section(storage, days=30)
    except Exception:
        perf_context = ""  # Don't fail if metrics unavailable

    return f"""You are a critical analyst reviewing trading strategy recommendations.

Your role:
- Review strategy signals generated by deterministic rules
- Identify potential blind spots or risks
- Flag unusual market conditions that rules might miss
- Provide second opinion, NOT override decisions

You are NOT:
- The primary decision maker (rules engine is)
- Generating buy/sell signals yourself
- Trading on behalf of users
- Providing financial advice
{perf_context}
{_get_fee_warning()}
Output format: Concise analysis in 2-3 sentences max."""


# Legacy constant for backward compatibility (deprecated)
SYSTEM_PROMPT = get_system_prompt.__doc__ or "Use get_system_prompt(storage) instead"

REVIEW_PROMPT_TEMPLATE = """Review this trading signal for potential issues:

Symbol: {symbol}
Signal: {signal_type} (strength: {signal_strength}/10)
Style: {trading_style}
Risk: {risk_level}

Reasoning from rules engine:
{rationale}

Current scores:
- Overall: {overall_score}
- Price: {price_score} (momentum: {price_change_pct}%)
- Technical: {technical_score} (RSI: {rsi}, Trend: {trend})
- Fundamental: {fundamental_score}

Recent news sentiment: {news_sentiment}

Question: Does this signal have obvious blind spots or unusual risks the rules might have missed?

Answer in 2-3 sentences. Focus on what rules CANNOT see (e.g., sector rotation, pending events, unusual correlations)."""

GUARDRAILS: GuardrailsDict = {
    "max_tokens": 200,  # Force brevity (2-3 sentences)
    "temperature": 0.3,  # Lower temp = more conservative/factual
    "forbidden_patterns": [
        r"\b(buy|sell|invest|trade)\b",  # No direct recommendations
        r"\bshould\b",  # No advice language
        r"\brecommend\b",  # No recommendations
        r"\bmust\b",  # No imperative commands
    ],
    "required_patterns": [
        r"\b(risk|concern|consider|note|caution)\b",  # Analytical language
    ],
}


def build_review_prompt(signal_data: dict[str, Any]) -> str:
    """Build review prompt from signal data.

    Args:
        signal_data: Signal from watchlist snapshot

    Returns:
        Formatted prompt string
    """
    return REVIEW_PROMPT_TEMPLATE.format(
        symbol=signal_data.get("symbol", "UNKNOWN"),
        signal_type=signal_data.get("signal_type", "HOLD"),
        signal_strength=signal_data.get("signal_strength", 5),
        trading_style=signal_data.get("recommended_style", "N/A"),
        risk_level=signal_data.get("risk_level", "MEDIUM"),
        rationale=signal_data.get("rationale", "No rationale provided"),
        overall_score=signal_data.get("current_score", {}).get("overall", 0),
        price_score=signal_data.get("current_score", {}).get("price", {}).get("score", 0),
        price_change_pct=signal_data.get("current_score", {})
        .get("price", {})
        .get("metadata", {})
        .get("raw_change_pct", 0),
        technical_score=signal_data.get("current_score", {}).get("technical", {}).get("score", 0),
        rsi=signal_data.get("current_score", {})
        .get("technical", {})
        .get("metadata", {})
        .get("rsi_14", 50),
        trend=signal_data.get("current_score", {})
        .get("technical", {})
        .get("metadata", {})
        .get("trend", "neutral"),
        fundamental_score=signal_data.get("current_score", {})
        .get("fundamental", {})
        .get("score", 0),
        news_sentiment=signal_data.get("news_sentiment_score", 0),
    )


def validate_review(review_text: str) -> tuple[bool, str]:
    """Validate LLM review against guardrails.

    Args:
        review_text: LLM response text

    Returns:
        (is_valid, reason)
    """
    # Check forbidden patterns (no direct trading advice)
    for pattern in GUARDRAILS["forbidden_patterns"]:
        if re.search(pattern, review_text, re.IGNORECASE):
            return False, f"Contains forbidden pattern: {pattern}"

    # Check required patterns (analytical language)
    has_required = any(
        re.search(pattern, review_text, re.IGNORECASE)
        for pattern in GUARDRAILS["required_patterns"]
    )
    if not has_required:
        return False, "Missing analytical language (risk/concern/consider/note/caution)"

    # Check length (should be concise)
    sentences = review_text.split(".")
    if len(sentences) > 5:
        return False, "Too verbose (>4 sentences)"

    return True, "Valid"
