-- Migration 052: Link strategies to trades and positions
-- Enables tracking which strategy generated each trade/position
-- Required for: performance tracking, validation, manual trade linking

-- 1. Add strategy_id to idea_outcomes (paper trades)
ALTER TABLE idea_outcomes
ADD COLUMN IF NOT EXISTS strategy_id UUID;

-- Add foreign key constraint (SET NULL on delete to preserve trade history)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'fk_idea_outcomes_strategy'
    ) THEN
        ALTER TABLE idea_outcomes
        ADD CONSTRAINT fk_idea_outcomes_strategy
            FOREIGN KEY (strategy_id)
            REFERENCES strategy_definitions(id)
            ON DELETE SET NULL;
    END IF;
END $$;

-- Index for efficient strategy-based queries
CREATE INDEX IF NOT EXISTS idx_idea_outcomes_strategy_id
ON idea_outcomes(strategy_id);

-- Compound index for strategy + date queries (common in performance calcs)
CREATE INDEX IF NOT EXISTS idx_idea_outcomes_strategy_date
ON idea_outcomes(strategy_id, created_at DESC);

-- 2. Add strategy_id to portfolio_positions (manual trades)
ALTER TABLE portfolio_positions
ADD COLUMN IF NOT EXISTS strategy_id UUID;

-- Add foreign key constraint
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'fk_portfolio_positions_strategy'
    ) THEN
        ALTER TABLE portfolio_positions
        ADD CONSTRAINT fk_portfolio_positions_strategy
            FOREIGN KEY (strategy_id)
            REFERENCES strategy_definitions(id)
            ON DELETE SET NULL;
    END IF;
END $$;

-- Index for efficient strategy-based queries
CREATE INDEX IF NOT EXISTS idx_portfolio_positions_strategy_id
ON portfolio_positions(strategy_id);

-- 3. Add strategy_id to backtest_runs (optional - for linking backtests to stored strategies)
ALTER TABLE backtest_runs
ADD COLUMN IF NOT EXISTS strategy_definition_id UUID;

-- Add foreign key constraint
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'fk_backtest_runs_strategy'
    ) THEN
        ALTER TABLE backtest_runs
        ADD CONSTRAINT fk_backtest_runs_strategy
            FOREIGN KEY (strategy_definition_id)
            REFERENCES strategy_definitions(id)
            ON DELETE SET NULL;
    END IF;
END $$;

-- Index for efficient strategy-based queries
CREATE INDEX IF NOT EXISTS idx_backtest_runs_strategy_id
ON backtest_runs(strategy_definition_id);

-- 4. Create strategy_signals table for daily signal storage
CREATE TABLE IF NOT EXISTS strategy_signals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    strategy_id UUID NOT NULL REFERENCES strategy_definitions(id) ON DELETE CASCADE,
    symbol VARCHAR(10) NOT NULL,
    signal_date DATE NOT NULL,
    signal_type VARCHAR(10) NOT NULL CHECK (signal_type IN ('BUY', 'HOLD', 'SELL', 'AVOID')),
    signal_strength INT NOT NULL CHECK (signal_strength >= 0 AND signal_strength <= 10),
    reasons TEXT[],
    market_data JSONB,  -- Snapshot of data used to generate signal
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    -- One signal per strategy per day
    UNIQUE(strategy_id, signal_date)
);

-- Indexes for efficient queries
CREATE INDEX IF NOT EXISTS idx_strategy_signals_strategy_date
ON strategy_signals(strategy_id, signal_date DESC);

CREATE INDEX IF NOT EXISTS idx_strategy_signals_date
ON strategy_signals(signal_date DESC);

CREATE INDEX IF NOT EXISTS idx_strategy_signals_type
ON strategy_signals(signal_type, signal_date DESC);

-- 5. Update table_registry
INSERT INTO table_registry (table_name, table_type, description)
VALUES
    ('strategy_signals', 'data', 'Daily trading signals generated by active strategies')
ON CONFLICT (table_name) DO UPDATE SET
    description = EXCLUDED.description;
