"""
Event replay backtest engine.

Implements simple date-loop replay over historical day_bars data.
Tracks portfolio state (cash, positions, equity curve) and executes trades based on strategy signals.

Phase A MVP: Single-symbol backtests with closing prices only (no slippage).
Phase B: Multi-symbol portfolio backtests with realistic fill simulation.
"""

import logging
from dataclasses import dataclass, field
from datetime import UTC, date, datetime, timedelta
from decimal import Decimal
from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    import pandas as pd
else:
    import pandas as pd

from app.analytics.indicators import _fetch_ohlcv_data, calculate_indicators_from_df
from app.backtest.models import BacktestEquity, BacktestTrade
from app.storage.facade import PortfolioStorage

logger = logging.getLogger(__name__)


@dataclass
class Position:
    """Open position within backtest."""

    symbol: str
    shares: int
    entry_price: Decimal
    entry_date: date
    max_favorable_pct: Decimal = Decimal("0.0")
    max_adverse_pct: Decimal = Decimal("0.0")

    def update_excursions(self, current_price: Decimal) -> None:
        """Update max favorable and max adverse excursions."""
        return_pct = (current_price - self.entry_price) / self.entry_price * Decimal("100.0")

        self.max_favorable_pct = max(self.max_favorable_pct, return_pct)

        self.max_adverse_pct = min(self.max_adverse_pct, return_pct)


@dataclass
class BacktestState:
    """Portfolio state during backtest.

    Tracks cash, open positions, completed trades, and equity curve.
    """

    cash: Decimal
    positions: dict[str, Position] = field(default_factory=dict)
    trades: list[BacktestTrade] = field(default_factory=list)
    equity_curve: list[BacktestEquity] = field(default_factory=list)
    peak_equity: Decimal = Decimal("0.0")

    def has_position(self, symbol: str) -> bool:
        """Check if symbol has open position."""
        return symbol in self.positions

    def get_position_value(self, symbol: str, current_price: Decimal) -> Decimal:
        """Calculate current market value of position."""
        if symbol not in self.positions:
            return Decimal("0.0")

        position = self.positions[symbol]
        return Decimal(str(position.shares)) * current_price

    def get_total_equity(self, current_prices: dict[str, Decimal]) -> Decimal:
        """Calculate total equity (cash + position values)."""
        position_value = sum(
            (self.get_position_value(symbol, current_prices[symbol]) for symbol in self.positions),
            Decimal("0.0"),  # Ensure Decimal type even with empty positions
        )
        return self.cash + position_value

    def record_equity_snapshot(
        self, run_id: str, backtest_date: date, current_prices: dict[str, Decimal]
    ) -> BacktestEquity:
        """Record daily equity snapshot."""
        position_value = sum(
            (self.get_position_value(symbol, current_prices[symbol]) for symbol in self.positions),
            Decimal("0.0"),  # Ensure Decimal type even with empty positions
        )
        equity = self.cash + position_value

        # Update peak equity
        self.peak_equity = max(self.peak_equity, equity)

        # Calculate drawdown from peak
        drawdown_pct = (
            (self.peak_equity - equity) / self.peak_equity * Decimal("100.0")
            if self.peak_equity > 0
            else Decimal("0.0")
        )

        snapshot = BacktestEquity(
            id="",  # Will be generated by DB
            run_id=run_id,
            date=backtest_date,
            equity=equity,
            cash=self.cash,
            position_value=Decimal(str(position_value)),
            drawdown_pct=drawdown_pct,
            created_at=datetime.now(UTC),  # Will be overridden by DB
        )

        self.equity_curve.append(snapshot)
        return snapshot


class Strategy(Protocol):
    """Strategy interface for backtest engine.

    Phase A MVP: SignalStrategy (wraps signal_classifier.py)
    Phase B: Custom strategies with parameter optimization
    """

    def should_enter(
        self,
        symbol: str,
        backtest_date: date,
        indicators: dict,  # type: ignore[type-arg]
        ohlcv: dict,  # type: ignore[type-arg]
    ) -> bool:
        """Determine if strategy should enter position."""
        ...

    def should_exit(
        self,
        position: Position,
        backtest_date: date,
        indicators: dict,  # type: ignore[type-arg]
        ohlcv: dict,  # type: ignore[type-arg]
    ) -> tuple[bool, str]:
        """Determine if strategy should exit position.

        Returns:
            (should_exit, exit_reason)
            exit_reason: "target", "stop", "signal", "time"
        """
        ...


def get_trading_days(
    storage: PortfolioStorage, symbol: str, start_date: date, end_date: date
) -> list[date]:
    """Query day_bars for chronological list of trading days.

    Args:
        storage: Database connection manager
        symbol: Stock symbol (e.g., "AAPL")
        start_date: Backtest start date
        end_date: Backtest end date

    Returns:
        List of trading days in chronological order

    Raises:
        ValueError: If no data found for symbol/date range
    """
    query = """
        SELECT DISTINCT date
        FROM day_bars
        WHERE symbol = $1
          AND date >= $2
          AND date <= $3
        ORDER BY date ASC
    """

    # Use PortfolioStorage.query() which returns Polars DataFrame
    result_df = storage.query(query, [symbol, str(start_date), str(end_date)])

    if result_df.is_empty():
        raise ValueError(f"No trading data found for {symbol} between {start_date} and {end_date}")

    return [row["date"] for row in result_df.to_dicts()]


def get_ohlcv(storage: PortfolioStorage, symbol: str, backtest_date: date) -> dict | None:  # type: ignore[type-arg]
    """Fetch OHLCV data for symbol on specific date.

    Args:
        storage: Database connection manager
        symbol: Stock symbol
        backtest_date: Date to fetch data for

    Returns:
        Dict with keys: open, high, low, close, volume, vwap
        None if no data found for date
    """
    query = """
        SELECT open, high, low, close, volume, vwap
        FROM day_bars
        WHERE symbol = $1 AND date = $2
        LIMIT 1
    """

    # Use PortfolioStorage.query() which returns Polars DataFrame
    result_df = storage.query(query, [symbol, str(backtest_date)])

    if result_df.is_empty():
        return None

    row = result_df.to_dicts()[0]
    return {
        "open": Decimal(str(row["open"])),
        "high": Decimal(str(row["high"])),
        "low": Decimal(str(row["low"])),
        "close": Decimal(str(row["close"])),
        "volume": int(row["volume"]) if row["volume"] else 0,
        "vwap": Decimal(str(row["vwap"])) if row["vwap"] else Decimal("0.0"),
    }


def calculate_position_size(
    cash: Decimal,
    price: Decimal,
    sizing_method: str,
    size_value: Decimal,
) -> int:
    """Calculate number of shares to buy.

    Args:
        cash: Available cash
        price: Current stock price
        sizing_method: "fixed_dollars" or "fixed_shares"
        size_value: Dollar amount or share count

    Returns:
        Number of shares to buy (0 if insufficient cash)
    """
    if sizing_method == "fixed_shares":
        shares = int(size_value)
        cost = Decimal(str(shares)) * price
        if cost > cash:
            return 0
        return shares

    # fixed_dollars
    shares = int(size_value / price)
    cost = Decimal(str(shares)) * price

    if cost > cash:
        return 0

    return shares


def enter_trade(
    state: BacktestState,
    symbol: str,
    backtest_date: date,
    price: Decimal,
    shares: int,
) -> None:
    """Enter position and update state.

    Args:
        state: Current backtest state
        symbol: Stock symbol
        backtest_date: Entry date
        price: Entry price
        shares: Number of shares to buy
    """
    cost = Decimal(str(shares)) * price
    state.cash -= cost

    position = Position(
        symbol=symbol,
        shares=shares,
        entry_price=price,
        entry_date=backtest_date,
    )

    state.positions[symbol] = position

    logger.debug(
        f"ENTER: {symbol} | Date: {backtest_date} | Shares: {shares} | Price: ${price:.2f} | Cost: ${cost:.2f}"
    )


def exit_trade(
    state: BacktestState,
    run_id: str,
    symbol: str,
    backtest_date: date,
    price: Decimal,
    exit_reason: str,
) -> BacktestTrade | None:
    """Exit position and record trade.

    Args:
        state: Current backtest state
        run_id: Backtest run ID
        symbol: Stock symbol
        backtest_date: Exit date
        price: Exit price
        exit_reason: Reason for exit ("target", "stop", "signal", "time", "eod")

    Returns:
        BacktestTrade record
    """
    if symbol not in state.positions:
        logger.warning(f"Attempted to exit non-existent position: {symbol}")
        return None

    position = state.positions.pop(symbol)

    proceeds = Decimal(str(position.shares)) * price
    state.cash += proceeds

    pnl = proceeds - (Decimal(str(position.shares)) * position.entry_price)
    pnl_pct = (price - position.entry_price) / position.entry_price * Decimal("100.0")

    trade = BacktestTrade(
        id="",  # Will be generated by DB
        run_id=run_id,
        symbol=symbol,
        entry_date=position.entry_date,
        entry_price=position.entry_price,
        exit_date=backtest_date,
        exit_price=price,
        shares=position.shares,
        pnl=pnl,
        pnl_pct=pnl_pct,
        exit_reason=exit_reason,  # type: ignore[arg-type]  # Literal type is correct at runtime
        max_favorable_pct=position.max_favorable_pct,
        max_adverse_pct=position.max_adverse_pct,
        created_at=datetime.now(UTC),  # Will be overridden by DB
    )

    state.trades.append(trade)

    logger.debug(
        f"EXIT: {symbol} | Date: {backtest_date} | Reason: {exit_reason} | "
        f"Price: ${price:.2f} | PnL: ${pnl:.2f} ({pnl_pct:.2f}%)"
    )

    return trade


class InsufficientDataError(Exception):
    """Raised when backtest requires more historical data than available."""

    def __init__(
        self,
        symbol: str,
        requested_start: date,
        requested_end: date,
        available_start: date | None,
        available_end: date | None,
    ):
        self.symbol = symbol
        self.requested_start = requested_start
        self.requested_end = requested_end
        self.available_start = available_start
        self.available_end = available_end

        if available_start is None:
            msg = f"No historical data for {symbol}. Need data from {requested_start} to {requested_end}."
        else:
            msg = (
                f"Insufficient historical data for {symbol}. "
                f"Requested: {requested_start} to {requested_end}, "
                f"Available: {available_start} to {available_end}."
            )
        super().__init__(msg)


INDICATOR_LOOKBACK_DAYS = 365


def _get_data_range(storage: PortfolioStorage, symbol: str) -> tuple[date | None, date | None]:
    """Get available date range for a symbol from day_bars.

    Args:
        storage: Database connection
        symbol: Stock symbol

    Returns:
        (min_date, max_date) or (None, None) if no data
    """
    query = """
        SELECT MIN(date) as min_date, MAX(date) as max_date
        FROM day_bars
        WHERE symbol = $1
    """
    result = storage.query(query, [symbol])
    if result.is_empty():
        return None, None

    row = result.to_dicts()[0]
    if row.get("min_date") is None:
        return None, None

    return row["min_date"], row["max_date"]


def replay_backtest(
    storage: PortfolioStorage,
    run_id: str,
    symbol: str,
    start_date: date,
    end_date: date,
    initial_capital: Decimal,
    strategy: Strategy,
    sizing_method: str = "fixed_dollars",
    size_value: Decimal = Decimal("10000.00"),
) -> BacktestState:
    """Execute backtest replay loop.

    Args:
        storage: Database connection manager
        run_id: Backtest run ID
        symbol: Stock symbol to backtest
        start_date: Backtest start date
        end_date: Backtest end date
        initial_capital: Starting cash
        strategy: Strategy implementation
        sizing_method: "fixed_dollars" or "fixed_shares"
        size_value: Dollar amount or share count

    Returns:
        Final backtest state with trades and equity curve

    Raises:
        InsufficientDataError: If historical data doesn't cover requested range
        ValueError: If no trading data found or invalid parameters
    """
    # Check data availability - raise specific error if insufficient
    data_min, data_max = _get_data_range(storage, symbol)

    if data_min is None or data_max is None:
        raise InsufficientDataError(symbol, start_date, end_date, None, None)

    # Check if we have data covering the requested range
    # If start_date is before available data, adjust to earliest available
    # (handles cases like requesting pre-IPO data)
    actual_start = start_date
    actual_end = end_date

    if start_date < data_min:
        logger.warning(
            f"Requested start {start_date} is before earliest data {data_min} for {symbol}. "
            f"Adjusting to {data_min} (possibly pre-IPO request)."
        )
        actual_start = data_min

    if end_date > data_max:
        logger.warning(
            f"Requested end {end_date} is after latest data {data_max} for {symbol}. "
            f"Adjusting to {data_max}."
        )
        actual_end = data_max

    # Ensure we have a valid date range
    if actual_start >= actual_end:
        raise InsufficientDataError(symbol, start_date, end_date, data_min, data_max)

    # Backtests need pre-start history for indicators such as SMA-200.
    required_lookback_start = actual_start - timedelta(days=INDICATOR_LOOKBACK_DAYS)
    if data_min > required_lookback_start:
        raise InsufficientDataError(symbol, start_date, end_date, data_min, data_max)

    logger.info(
        f"Starting backtest: {symbol} | {actual_start} to {actual_end} | Capital: ${initial_capital:.2f}"
        + (
            f" (adjusted from {start_date}-{end_date})"
            if actual_start != start_date or actual_end != end_date
            else ""
        )
    )

    # Use adjusted dates for the backtest
    start_date = actual_start
    end_date = actual_end

    # Initialize state (convert to Decimal for precision)
    initial_capital_dec = Decimal(str(initial_capital))
    state = BacktestState(cash=initial_capital_dec, peak_equity=initial_capital_dec)

    # 1. Fetch ALL data at once (optimization)
    # We need data from (start_date - lookback) to end_date
    # 365 days lookback ensures we have enough for 200-day MA even with weekends/holidays
    lookback_days = INDICATOR_LOOKBACK_DAYS
    data_start_date = start_date - timedelta(days=lookback_days)

    logger.info(f"Fetching bulk OHLCV data for {symbol} from {data_start_date} to {end_date}")

    # Use the internal fetcher from indicators module or direct query
    # We'll use a direct query here for efficiency to get a DataFrame

    # Fetch all data in one go
    full_df = _fetch_ohlcv_data(
        storage,
        symbol,
        lookback_days=10000,  # Large number to get everything in range
        as_of_date=end_date,
    )

    if full_df.empty:
        logger.error(f"No data found for {symbol}")
        raise ValueError(f"No trading data found for {symbol}")

    # Filter for our specific range if needed, though _fetch_ohlcv_data does some limiting
    # Ensure we have data up to end_date

    # Get trading days within the backtest period
    # Filter df where date >= start_date and date <= end_date
    mask = (full_df.index >= pd.Timestamp(start_date)) & (full_df.index <= pd.Timestamp(end_date))
    trading_days_df = full_df.loc[mask]

    if trading_days_df.empty:
        logger.error(f"No trading days found between {start_date} and {end_date}")
        raise ValueError(f"No trading data found for {symbol} in requested period")

    trading_days = [d.date() for d in trading_days_df.index]
    logger.info(f"Running backtest over {len(trading_days)} trading days")

    # Main Loop
    for backtest_date in trading_days:
        # Slice the dataframe to get data up to this date
        # We need enough history for indicators (e.g. 250 rows)
        # Using .loc[:backtest_date] gets everything up to and including that date
        current_data_slice = full_df.loc[: pd.Timestamp(backtest_date)]

        # We only need the last N rows for indicators to save memory/processing
        # 300 is safe for 200 SMA
        if len(current_data_slice) > 300:
            current_data_slice = current_data_slice.iloc[-300:]

        if current_data_slice.empty:
            continue

        # Get current day's OHLCV (last row)
        current_bar = current_data_slice.iloc[-1]
        ohlcv = {
            "open": float(current_bar["open"]),
            "high": float(current_bar["high"]),
            "low": float(current_bar["low"]),
            "close": float(current_bar["close"]),
            "volume": float(current_bar["volume"]),
        }

        # Calculate indicators using the slice
        # This avoids a DB call
        indicators_result = calculate_indicators_from_df(current_data_slice, symbol)
        indicators = indicators_result["indicators"]

        # Update excursions for open positions
        current_price = Decimal(str(ohlcv["close"]))  # Convert float to Decimal
        for pos in state.positions.values():
            pos.update_excursions(current_price)

        # Check exits first
        for symbol_check in list(state.positions.keys()):
            position = state.positions[symbol_check]
            should_exit, exit_reason = strategy.should_exit(
                position, backtest_date, indicators, ohlcv
            )
            if should_exit:
                exit_trade(state, run_id, symbol_check, backtest_date, current_price, exit_reason)

        # Check entries (if no position)
        if not state.has_position(symbol) and strategy.should_enter(
            symbol, backtest_date, indicators, ohlcv
        ):
            shares = calculate_position_size(state.cash, current_price, sizing_method, size_value)
            if shares > 0:
                enter_trade(state, symbol, backtest_date, current_price, shares)

        # Record daily equity snapshot
        current_prices = {symbol: current_price}
        state.record_equity_snapshot(run_id, backtest_date, current_prices)

    # Close any open positions at end of backtest (mark-to-market)
    final_date = trading_days[-1]
    final_ohlcv = get_ohlcv(storage, symbol, final_date)
    if final_ohlcv:
        final_price = final_ohlcv["close"]
        for symbol_check in list(state.positions.keys()):
            exit_trade(state, run_id, symbol_check, final_date, final_price, "eod")

    logger.info(
        f"Backtest complete: {len(state.trades)} trades | "
        f"Final equity: ${state.equity_curve[-1].equity:.2f}"
    )

    return state
